version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    restart: unless-stopped
    volumes:
      - ".:/app"
    ports:
      - 3000:3000
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && yarn start"

  test:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: ["yarn", "test"]
